_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.11.6
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.6
            "5": 0.19.5
            "6": 4.51.3
            "8":
                - 1
                - 5
            "12": 0.19.5
            "13": darwin-x86_64
